working on github action.

diff --git a/.github/workflows/develop.yml b/.github/workflows/develop.yml
--- a/.github/workflows/develop.yml
+++ b/.github/workflows/develop.yml
@@ -79,5 +79,40 @@ jobs:
         port: ${{ env.REMOTE_PORT }}
         key: ${{ env.DEPLOY_KEY }}
         script: |
-          git clone git@github.com:kawinpromsopa/${{env.GITHUB_REPOSITORY_NAME }}.git --branch ${{ env.GITHUB_BRANCH }}
-          bash ${{env.GITHUB_REPOSITORY_NAME }}/.github/deploy.sh ${{ env.GITHUB_ACTIONS }} ${{env.GITHUB_REPOSITORY_NAME }} ${{ env.GITHUB_BRANCH }} ${{ env.AWS_ACCOUNT_ID }} ${{ env.AWS_REGION }}
+          ##
+          ## Setup Pipeline Compose Environment
+          ##
+          if [[ ${{ env.GITHUB_BRANCH_NAME }} =~ ^(develop)$ ]]; then
+            export PIPELINE_COMPOSE_ENVIRONMENT=dev
+          elif  [[ ${{ env.GITHUB_BRANCH_NAME }} =~ ^(main)$ ]]; then
+            export PIPELINE_COMPOSE_ENVIRONMENT=production
+          fi
+          ##
+          ## Setup AWS ECR authentication
+          ##
+          aws ecr get-login-password --region ${{ env.GITHUB_AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.GITHUB_AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
+          if [[ "$?" -eq 0 ]]; then
+            echo "AWS Elastic Container Registry Authenticated."
+          else
+            echo "AWS Elastic Container Registry Authenticate FAILED!."
+            exit 1
+          fi
+          ##
+          ## Deploy Application
+          ##
+          if [[ ${{ env.GITHUB_ACTIONS }} == true ]]; then
+            echo "Docker Image Latest Version Downloading..."
+            docker-compose -f "${PIPELINE_COMPOSE_ENVIRONMENT}"-simple-web/docker-compose.yml pull
+            echo "Docker Image Latest Version Download Success."
+          
+            echo "Application Deploying..."
+            docker-compose -f "${PIPELINE_COMPOSE_ENVIRONMENT}"-simple-web/docker-compose.yml up -d
+          
+            if [[ "$?" -eq 0 ]]; then
+              echo "Application Deployed.."
+              rm -rf ${{ env.GITHUB_REPOSITORY_NAME }}
+            else
+              echo "Application FAILED."
+              rm -rf ${{ env.GITHUB_REPOSITORY_NAME }}
+            fi
+          fi
